// Canonical Intelligence Platform(tm) -- Scan Orchestrator Type Constants

export const LIFECYCLE_STAGES = Object.freeze({
  SCAN_REQUESTED:          'SCAN_REQUESTED',
  CONNECTORS_STARTED:      'CONNECTORS_STARTED',
  EVIDENCE_COLLECTED:      'EVIDENCE_COLLECTED',
  REGISTRY_COMPLETE:       'REGISTRY_COMPLETE',
  NORMALIZATION_COMPLETE:  'NORMALIZATION_COMPLETE',
  RESOLUTION_COMPLETE:     'RESOLUTION_COMPLETE',
  DOMAINS_REFRESHED:       'DOMAINS_REFRESHED',
  SCAN_COMPLETE:           'SCAN_COMPLETE',
  SCAN_FAILED:             'SCAN_FAILED',
  SCAN_CANCELLED:          'SCAN_CANCELLED',
  SCAN_TIMED_OUT:          'SCAN_TIMED_OUT',
});

export const SCAN_STATUSES = Object.freeze({
  PENDING:    'PENDING',
  RUNNING:    'RUNNING',
  WAITING:    'WAITING',
  COMPLETED:  'COMPLETED',
  FAILED:     'FAILED',
  CANCELLED:  'CANCELLED',
  TIMED_OUT:  'TIMED_OUT',
});

export const ORCHESTRATOR_EVENTS = Object.freeze({
  SCAN_REQUESTED:           'SCAN_REQUESTED',
  CONNECTORS_STARTED:       'CONNECTORS_STARTED',
  CONNECTOR_STARTED:        'CONNECTOR_STARTED',
  CONNECTOR_COMPLETED:      'CONNECTOR_COMPLETED',
  CONNECTOR_FAILED:         'CONNECTOR_FAILED',
  EVIDENCE_COLLECTED:       'EVIDENCE_COLLECTED',
  REGISTRY_COMPLETE:        'REGISTRY_COMPLETE',
  NORMALIZATION_COMPLETE:   'NORMALIZATION_COMPLETE',
  RESOLUTION_COMPLETE:      'RESOLUTION_COMPLETE',
  DOMAINS_REFRESHED:        'DOMAINS_REFRESHED',
  SCAN_COMPLETED:           'SCAN_COMPLETED',
  SCAN_FAILED:              'SCAN_FAILED',
  SCAN_CANCELLED:           'SCAN_CANCELLED',
  SCAN_TIMED_OUT:           'SCAN_TIMED_OUT',
  PIPELINE_STAGE_STARTED:   'PIPELINE_STAGE_STARTED',
  PIPELINE_STAGE_COMPLETED: 'PIPELINE_STAGE_COMPLETED',
  PIPELINE_STAGE_FAILED:    'PIPELINE_STAGE_FAILED',
});

export const ORCHESTRATOR_ERROR_CODES = Object.freeze({
  INVALID_SCAN_REQUEST:      'INVALID_SCAN_REQUEST',
  CONNECTOR_FAILURE:         'CONNECTOR_FAILURE',
  REGISTRY_FAILURE:          'REGISTRY_FAILURE',
  NORMALIZATION_FAILURE:     'NORMALIZATION_FAILURE',
  RESOLUTION_FAILURE:        'RESOLUTION_FAILURE',
  DOMAIN_REFRESH_FAILURE:    'DOMAIN_REFRESH_FAILURE',
  PIPELINE_TIMEOUT:          'PIPELINE_TIMEOUT',
  INVALID_STATE_TRANSITION:  'INVALID_STATE_TRANSITION',
  SCAN_NOT_FOUND:            'SCAN_NOT_FOUND',
  PIPELINE_ORDER_VIOLATION:  'PIPELINE_ORDER_VIOLATION',
  CANCELLATION_REQUESTED:    'CANCELLATION_REQUESTED',
  EXECUTOR_NOT_FOUND:        'EXECUTOR_NOT_FOUND',
});

// The ordered happy-path lifecycle. Terminal error stages are not included.
export const LIFECYCLE_STAGE_ORDER = Object.freeze([
  LIFECYCLE_STAGES.SCAN_REQUESTED,
  LIFECYCLE_STAGES.CONNECTORS_STARTED,
  LIFECYCLE_STAGES.EVIDENCE_COLLECTED,
  LIFECYCLE_STAGES.REGISTRY_COMPLETE,
  LIFECYCLE_STAGES.NORMALIZATION_COMPLETE,
  LIFECYCLE_STAGES.RESOLUTION_COMPLETE,
  LIFECYCLE_STAGES.DOMAINS_REFRESHED,
  LIFECYCLE_STAGES.SCAN_COMPLETE,
]);

export const TERMINAL_STAGES = new Set([
  LIFECYCLE_STAGES.SCAN_COMPLETE,
  LIFECYCLE_STAGES.SCAN_FAILED,
  LIFECYCLE_STAGES.SCAN_CANCELLED,
  LIFECYCLE_STAGES.SCAN_TIMED_OUT,
]);

// Maps lifecycle completion stages to the executor key that produces them.
// CONNECTORS_STARTED has no executor — it is a "begin" marker; EVIDENCE_COLLECTED is the result.
export const STAGE_EXECUTOR_MAP = Object.freeze({
  [LIFECYCLE_STAGES.EVIDENCE_COLLECTED]:       'connectors',
  [LIFECYCLE_STAGES.REGISTRY_COMPLETE]:        'registry',
  [LIFECYCLE_STAGES.NORMALIZATION_COMPLETE]:   'normalization',
  [LIFECYCLE_STAGES.RESOLUTION_COMPLETE]:      'resolution',
  [LIFECYCLE_STAGES.DOMAINS_REFRESHED]:        'domains',
});

export const EXECUTOR_KEYS = Object.freeze(['connectors', 'registry', 'normalization', 'resolution', 'domains']);
