// Canonical Intelligence Platform(tm) -- Text Normalization Rules
//
// TEXT category rules apply broadly to all string values regardless of field name.
// They standardize whitespace, unicode representation, and quote characters.
// Applied first in the pipeline so all subsequent rules receive clean input.

import { NORMALIZATION_CATEGORIES, RULE_STATUSES, NORMALIZER_INPUT_TYPES } from '../types.js';
import {
  trimWhitespace,
  collapseSpaces,
  normalizeUnicodeNfc,
  normalizeStraightQuotes,
  normalizeApostrophe,
  normalizeEmptyString,
  normalizeUndefined,
} from '../transformers.js';

export const TEXT_RULES = [
  {
    ruleId:      'TXT-001',
    ruleName:    'Trim Whitespace',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.STRING,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Remove leading and trailing whitespace from string values.',
    example:     { input: '  The Weeknd  ', output: 'The Weeknd' },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   trimWhitespace,
  },
  {
    ruleId:      'TXT-002',
    ruleName:    'Collapse Internal Spaces',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.STRING,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Replace runs of internal whitespace (spaces, tabs, newlines) with a single space.',
    example:     { input: 'The  Weeknd', output: 'The Weeknd' },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   collapseSpaces,
  },
  {
    ruleId:      'TXT-003',
    ruleName:    'Normalize Unicode NFC',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.STRING,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Normalize Unicode to NFC canonical composition form. Ensures consistent byte representation of accented characters.',
    example:     { input: 'é', output: 'é' },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   normalizeUnicodeNfc,
  },
  {
    ruleId:      'TXT-004',
    ruleName:    'Normalize Straight Quotes',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.STRING,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Replace curly/smart double and single quote characters with straight ASCII equivalents.',
    example:     { input: '“Hello”', output: '"Hello"' },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   normalizeStraightQuotes,
  },
  {
    ruleId:      'TXT-005',
    ruleName:    'Normalize Apostrophes',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.STRING,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Replace typographic apostrophes and similar Unicode characters with the ASCII apostrophe.',
    example:     { input: "it’s", output: "it's" },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   normalizeApostrophe,
  },
  {
    ruleId:      'TXT-006',
    ruleName:    'Normalize Empty Strings',
    inputType:   NORMALIZER_INPUT_TYPES.STRING,
    outputType:  NORMALIZER_INPUT_TYPES.NULLABLE,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Convert empty or whitespace-only strings to null. Prevents downstream handling of zero-length strings as meaningful values.',
    example:     { input: '   ', output: null },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   normalizeEmptyString,
  },
  {
    ruleId:      'TXT-007',
    ruleName:    'Normalize Undefined to Null',
    inputType:   NORMALIZER_INPUT_TYPES.NULLABLE,
    outputType:  NORMALIZER_INPUT_TYPES.NULLABLE,
    version:     '1.0.0',
    category:    NORMALIZATION_CATEGORIES.TEXT,
    description: 'Convert undefined values to null. Royalte uses null as the canonical representation of absent data.',
    example:     { input: undefined, output: null },
    status:      RULE_STATUSES.ACTIVE,
    normalize:   normalizeUndefined,
  },
];
