// ─────────────────────────────────────────────────────────────────────────
// Royaltē Identity Graph™ — temporary seed layer
//
// Constitutional Architecture: identity exists outside the scan engine.
// Engine reads from here. Engine writes nothing. Engine owns no
// artist-specific records — ever.
//
// Future: replace data source with Supabase verified_artist_identity
// table (and its supporting tables for cross-platform identifier links).
// The function signatures exported from this module are the engine's
// contract; the data source backing them is an implementation detail.
//
// Engine logic in run-scan.js never changes when identity data updates.
// Adding a new verified artist is a pure data operation against this
// module (today: edit this file; tomorrow: insert into Supabase). No
// engine code change, no PR review of the engine, no redeploy of the
// engine logic.
//
// What this module DOES NOT contain:
//   - Search heuristics
//   - Matching algorithms
//   - Verification policy decisions
//   - Engine state
// What this module DOES contain:
//   - Curated cross-platform identifier mappings (canonical name → IDs
//     on YouTube, future Bandcamp, future Patreon, future Instagram…)
//   - Sourcing metadata (who curated, when, why)
//   - Read-only lookup helpers
//
// Governance Directive Rule 1: every curated entry is a Constitutional
// decision. New entries require explicit founder ratification.
// ─────────────────────────────────────────────────────────────────────────

// Verified YouTube channels for canonical artists.
// Key: canonical artist name, normalized (lowercase, trimmed).
// Value: official artist-owned YouTube channel ID.
//
// Topic channels are auto-generated by YouTube for distributed music and
// are NOT artist-owned, so they CANNOT represent canonical identity and
// MUST NOT appear here. Only official artist-owned channels qualify.
const VERIFIED_YOUTUBE_CHANNELS = {
  'black alternative': {
    channelId:    'UCOIO07KGdBFp9Ej40iaZRGQ', // Black Alternative (official)
    addedAt:      '2026-06-09',
    addedBy:      'founder',
    note:         "Official channel; title 'Black Alternative Music' diverges from canonical name.",
  },
};

/**
 * Look up a verified YouTube channel ID for a canonical artist name.
 *
 * @param {string} artistName  Canonical artist name (any casing — normalized internally).
 * @returns {string|null}      Channel ID when present in the graph; null otherwise.
 */
export function lookupYouTubeChannelId(artistName) {
  const key = (artistName || '').toLowerCase().trim();
  const entry = VERIFIED_YOUTUBE_CHANNELS[key];
  return entry ? entry.channelId : null;
}

/**
 * Reserved for future expansion — read-only access to a verified entry's
 * full metadata (sourcing, timestamps, notes). Useful for the future
 * Mission Control display ("this identity verified by … on …").
 *
 * @param {string} artistName
 * @returns {object|null}
 */
export function getYouTubeChannelEntry(artistName) {
  const key = (artistName || '').toLowerCase().trim();
  return VERIFIED_YOUTUBE_CHANNELS[key] || null;
}
