// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Backend Verification™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Backend Verification™ owns all fields describing HOW WELL the artist's
// catalog is verified across the backend: per-provider verification status,
// catalog match rate, and overall verification score.
//
// ─────────────────────────────────────────────────────────────────────────────

export const BACKEND_FIELDS = Object.freeze([
  {
    id:               'backend.apple_verified',
    canonicalName:    'apple_verified',
    displayName:      'Apple Music Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED presence on Apple Music.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.spotify_verified',
    canonicalName:    'spotify_verified',
    displayName:      'Spotify Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED presence on Spotify.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['spotify'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.youtube_verified',
    canonicalName:    'youtube_verified',
    displayName:      'YouTube Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED Official Artist Channel on YouTube.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['youtube'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.deezer_verified',
    canonicalName:    'deezer_verified',
    displayName:      'Deezer Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED presence on Deezer.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['deezer'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.tidal_verified',
    canonicalName:    'tidal_verified',
    displayName:      'TIDAL Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED presence on TIDAL.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['tidal'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.musicbrainz_verified',
    canonicalName:    'musicbrainz_verified',
    displayName:      'MusicBrainz Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED record in MusicBrainz.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['musicbrainz'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.discogs_verified',
    canonicalName:    'discogs_verified',
    displayName:      'Discogs Verified',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Whether the artist has a VERIFIED entry in the Discogs catalog.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['discogs'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.catalog_match_rate',
    canonicalName:    'catalog_match_rate',
    displayName:      'Catalog Match Rate',
    parentObject:     'Artist',
    domain:           'Backend Verification',
    description:      'Percentage of Spotify top tracks found in the Apple Music catalog via ISRC cross-reference.',
    dataType:         'percent',
    required:         false,
    defaultValue:     null,
    validationRule:   '0–100 inclusive',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['apple', 'spotify'],
    consumers:        ['BackendIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
