// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Catalog™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Catalog™ owns all fields describing WHAT an artist has released:
// release and track counts, primary release, ISRC coverage, and
// catalog composition.
//
// ─────────────────────────────────────────────────────────────────────────────

export const CATALOG_FIELDS = Object.freeze([
  {
    id:               'catalog.release_count',
    canonicalName:    'release_count',
    displayName:      'Release Count',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Total number of releases (albums + EPs + singles) in the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.track_count',
    canonicalName:    'track_count',
    displayName:      'Track Count',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Total number of individual tracks across all releases in the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.primary_release',
    canonicalName:    'primary_release',
    displayName:      'Primary Release',
    parentObject:     'Release',
    domain:           'Catalog',
    description:      'Best-verified or most prominent release in the artist\'s catalog, used as the primary reference.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['apple', 'spotify'],
    consumers:        ['CatalogIntelligence', 'IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.primary_track',
    canonicalName:    'primary_track',
    displayName:      'Primary Track',
    parentObject:     'Track',
    domain:           'Catalog',
    description:      'Most-streamed or best-verified track, used as the primary single-track reference.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['apple', 'spotify'],
    consumers:        ['CatalogIntelligence', 'IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.total_isrcs',
    canonicalName:    'total_isrcs',
    displayName:      'Total ISRCs',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Total number of unique ISRCs verified across the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'AGGREGATED',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.isrc_coverage_percent',
    canonicalName:    'isrc_coverage_percent',
    displayName:      'ISRC Coverage',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Percentage of tracks with a verified ISRC (total_isrcs / track_count × 100).',
    dataType:         'percent',
    required:         false,
    defaultValue:     0,
    validationRule:   '0–100 inclusive',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   [],
    consumers:        ['CatalogIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.album_count',
    canonicalName:    'album_count',
    displayName:      'Album Count',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Count of full-length albums (7+ tracks) in the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.ep_count',
    canonicalName:    'ep_count',
    displayName:      'EP Count',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Count of EPs (2–6 tracks) in the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'catalog.single_count',
    canonicalName:    'single_count',
    displayName:      'Single Count',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Count of singles (1 track) in the artist\'s catalog.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['CatalogIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'backend.catalog_match_rate',
    canonicalName:    'catalog_match_rate',
    displayName:      'Catalog Match Rate',
    parentObject:     'Artist',
    domain:           'Catalog',
    description:      'Percentage of Spotify top tracks found in the Apple Music catalog via ISRC cross-reference.',
    dataType:         'percent',
    required:         false,
    defaultValue:     null,
    validationRule:   '0–100 inclusive',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['apple', 'spotify'],
    consumers:        ['CatalogIntelligence', 'Health Intelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
