// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Distribution Availability™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Distribution Availability™ owns canonical availability facts: where the
// artist's catalog exists across countries, territories, and platforms.
// This domain does NOT duplicate connector logic performed by Identity or Catalog.
// It consumes shared evidence collected once by the platform.
//
// ─────────────────────────────────────────────────────────────────────────────

export const DISTRIBUTION_FIELDS = Object.freeze([
  {
    id:               'distribution.country_count',
    canonicalName:    'country_count',
    displayName:      'Country Count',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Number of countries where the artist\'s catalog is available on Apple Music.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer, max 167',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['GlobalFootprintIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.platform_count',
    canonicalName:    'platform_count',
    displayName:      'Platform Count',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Number of platforms where the artist\'s catalog has a verified presence.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'VERIFICATION_COUNT',
    sourcePriority:   [],
    consumers:        ['GlobalFootprintIntelligence', 'IdentityIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.global_availability_status',
    canonicalName:    'global_availability_status',
    displayName:      'Global Availability',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Summary availability status across all 167 Apple Music storefronts: WIDE | MODERATE | LIMITED | MINIMAL.',
    dataType:         'enum',
    required:         false,
    defaultValue:     null,
    validationRule:   'WIDE|MODERATE|LIMITED|MINIMAL',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['GlobalFootprintIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.big6_availability',
    canonicalName:    'big6_availability',
    displayName:      'BIG6 Availability',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Per-storefront availability map for the 8 key revenue markets (US, CA, GB, DE, FR, JP, AU, BR).',
    dataType:         'object',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['GlobalFootprintIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.primary_markets',
    canonicalName:    'primary_markets',
    displayName:      'Primary Markets',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Ordered list of top markets by catalog presence, derived from storefront availability data.',
    dataType:         'array',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['GlobalFootprintIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.apple_storefront_count',
    canonicalName:    'apple_storefront_count',
    displayName:      'Apple Storefronts',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Number of Apple Music storefronts (out of 167) where the artist\'s catalog is available.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer, max 167',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['GlobalFootprintIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'distribution.spotify_market_count',
    canonicalName:    'spotify_market_count',
    displayName:      'Spotify Markets',
    parentObject:     'Artist',
    domain:           'Distribution Availability',
    description:      'Number of Spotify markets where the artist\'s catalog is available.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['spotify'],
    consumers:        ['GlobalFootprintIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
