// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Identity™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Identity™ owns all fields that describe WHO an artist is: canonical name,
// platform profiles, verification coverage, and identity confidence.
//
// Apple Music is the canonical identity source (constitutional, PR #108).
// All other providers are verification sources.
//
// ─────────────────────────────────────────────────────────────────────────────

export const IDENTITY_FIELDS = Object.freeze([
  {
    id:               'identity.artist_name',
    canonicalName:    'artist_name',
    displayName:      'Artist Name',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Canonical display name of the artist, resolved from Apple Music as the authoritative source.',
    dataType:         'string',
    required:         true,
    defaultValue:     null,
    validationRule:   'non-empty string',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['IdentityIntelligence', 'HealthEngine', 'ExecutiveBrief', 'MissionControl', 'ScanUI'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.artist_image',
    canonicalName:    'artist_image',
    displayName:      'Artist Image',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'High-resolution artist image URL (600×600). Apple Music is the canonical image source.',
    dataType:         'url',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify'],
    consumers:        ['MissionControl', 'ScanUI', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.primary_genre',
    canonicalName:    'primary_genre',
    displayName:      'Primary Genre',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Primary musical genre of the artist as reported by Apple Music.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['IdentityIntelligence', 'MissionControl', 'ScanUI'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.storefront',
    canonicalName:    'storefront',
    displayName:      'Apple Storefront',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Apple Music regional storefront code used to resolve this artist (e.g. "us", "gb").',
    dataType:         'string',
    required:         false,
    defaultValue:     'us',
    validationRule:   '2-letter ISO storefront code',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'STATIC',
    sourcePriority:   ['apple'],
    consumers:        ['IdentityIntelligence', 'CIOAssembler'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.apple_artist_id',
    canonicalName:    'apple_artist_id',
    displayName:      'Apple Music Artist ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Apple Music catalog artist ID. Permanent stable identifier assigned by Apple.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   'numeric string',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['IdentityIntelligence', 'CIOAssembler', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.apple_artist_url',
    canonicalName:    'apple_artist_url',
    displayName:      'Apple Music Artist URL',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Canonical Apple Music artist page URL.',
    dataType:         'url',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple'],
    consumers:        ['IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.spotify_artist_id',
    canonicalName:    'spotify_artist_id',
    displayName:      'Spotify Artist ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Spotify catalog artist ID. Primary verification cross-reference against Apple.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   'alphanumeric Spotify ID',
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'ISRC_VERIFIED',
    sourcePriority:   ['spotify'],
    consumers:        ['IdentityIntelligence', 'CIOAssembler', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.youtube_channel_id',
    canonicalName:    'youtube_channel_id',
    displayName:      'YouTube Channel ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'YouTube Official Artist Channel ID.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['youtube'],
    consumers:        ['IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.deezer_artist_id',
    canonicalName:    'deezer_artist_id',
    displayName:      'Deezer Artist ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Deezer catalog artist ID.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['deezer'],
    consumers:        ['IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.tidal_artist_id',
    canonicalName:    'tidal_artist_id',
    displayName:      'TIDAL Artist ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'TIDAL catalog artist ID.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['tidal'],
    consumers:        ['IdentityIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.musicbrainz_id',
    canonicalName:    'musicbrainz_id',
    displayName:      'MusicBrainz Artist ID',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'MusicBrainz MBID for the artist — canonical open-standard identity.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'HIGHEST_CONFIDENCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['musicbrainz'],
    consumers:        ['IdentityIntelligence', 'CIOAssembler'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.verified_providers',
    canonicalName:    'verified_providers',
    displayName:      'Verified Providers',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Count of identity providers that returned VERIFIED status for this artist.',
    dataType:         'number',
    required:         true,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'VERIFICATION_COUNT',
    sourcePriority:   [],
    consumers:        ['IdentityIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.total_providers',
    canonicalName:    'total_providers',
    displayName:      'Total Providers',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Total count of canonical identity providers evaluated in this scan.',
    dataType:         'number',
    required:         true,
    defaultValue:     5,
    validationRule:   'positive integer',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['IdentityIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.coverage_percent',
    canonicalName:    'coverage_percent',
    displayName:      'Identity Coverage',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Percentage of canonical identity providers that returned VERIFIED (verified_providers / total_providers × 100).',
    dataType:         'percent',
    required:         true,
    defaultValue:     0,
    validationRule:   '0–100 inclusive',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'VERIFICATION_COUNT',
    sourcePriority:   [],
    consumers:        ['IdentityIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'identity.artist_confidence',
    canonicalName:    'artist_confidence',
    displayName:      'Artist Confidence',
    parentObject:     'Artist',
    domain:           'Identity',
    description:      'Overall confidence in the artist identity record: HIGH | MEDIUM | LOW | UNKNOWN.',
    dataType:         'enum',
    required:         true,
    defaultValue:     'UNKNOWN',
    validationRule:   'HIGH|MEDIUM|LOW|UNKNOWN',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   [],
    consumers:        ['IdentityIntelligence', 'HealthEngine', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
