// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Monitoring™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Monitoring™ owns all fields tracking CHANGE OVER TIME: scan history,
// detected changes, alerts, health trend, and aggregated executive metrics.
//
// Note on executive.* field IDs:
//   The brief defines stable IDs with the "executive." prefix for
//   health-aggregated fields. These fields are OWNED by Monitoring™
//   (the domain that computes them) and CONSUMED by Executive Intelligence™.
//   Constitutional rule: Executive Intelligence never owns fields.
//   The "executive." prefix is a stable namespace, not a domain claim.
//
// ─────────────────────────────────────────────────────────────────────────────

export const MONITORING_FIELDS = Object.freeze([
  {
    id:               'monitoring.last_scan',
    canonicalName:    'last_scan',
    displayName:      'Last Scan',
    parentObject:     'Scan',
    domain:           'Monitoring',
    description:      'ISO 8601 timestamp of the most recent completed scan for this artist.',
    dataType:         'date',
    required:         false,
    defaultValue:     null,
    validationRule:   'ISO 8601 datetime string',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.scan_count',
    canonicalName:    'scan_count',
    displayName:      'Scan Count',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Total number of scans completed for this artist in the Royaltē system.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.change_count',
    canonicalName:    'change_count',
    displayName:      'Changes Detected',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Number of changes detected between the most recent scan and the previous scan.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'HealthEngine', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.alert_count',
    canonicalName:    'alert_count',
    displayName:      'Active Alerts',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Number of unresolved alerts currently active for this artist.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.health_trend',
    canonicalName:    'health_trend',
    displayName:      'Health Trend',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Direction of health score movement across recent scans: IMPROVING | STABLE | DECLINING | UNKNOWN.',
    dataType:         'enum',
    required:         false,
    defaultValue:     'UNKNOWN',
    validationRule:   'IMPROVING|STABLE|DECLINING|UNKNOWN',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'HealthEngine', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.last_change_type',
    canonicalName:    'last_change_type',
    displayName:      'Last Change Type',
    parentObject:     'ChangeEvent',
    domain:           'Monitoring',
    description:      'Category of the most recently detected change (CATALOG_UPDATE, RIGHTS_CHANGE, DISTRIBUTION_CHANGE, etc.).',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  // ── executive.* namespace — owned by Monitoring, consumed by Executive Intelligence ──────
  {
    id:               'executive.health_score',
    canonicalName:    'health_score',
    displayName:      'Health Score',
    parentObject:     'HealthIndicator',
    domain:           'Monitoring',
    description:      'Composite health score (0–100) computed by the Royaltē Health Engine™ from all domain signals.',
    dataType:         'number',
    required:         false,
    defaultValue:     null,
    validationRule:   '0–100 inclusive',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['HealthEngine', 'ExecutiveBrief', 'MissionControl', 'ScanUI'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'executive.health_grade',
    canonicalName:    'health_grade',
    displayName:      'Health Grade',
    parentObject:     'HealthIndicator',
    domain:           'Monitoring',
    description:      'Letter-grade summary of the health score: A+ | A | B | C | D | F.',
    dataType:         'enum',
    required:         false,
    defaultValue:     null,
    validationRule:   'A+|A|B|C|D|F',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['HealthEngine', 'ExecutiveBrief', 'MissionControl', 'ScanUI'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'executive.priority_actions',
    canonicalName:    'priority_actions',
    displayName:      'Priority Actions',
    parentObject:     'ExecutiveInsight',
    domain:           'Monitoring',
    description:      'Ordered list of high-priority recommended actions sourced strictly from the Health Engine intelligence report.',
    dataType:         'array',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['ExecutiveBrief', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'executive.ai_insight',
    canonicalName:    'ai_insight',
    displayName:      'AI Insight',
    parentObject:     'ExecutiveInsight',
    domain:           'Monitoring',
    description:      'ATHENA™-generated natural-language insight synthesized from all domain intelligence for this scan.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['ExecutiveBrief', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
