// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Monitoring™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Monitoring™ owns all fields tracking CHANGE OVER TIME for an artist:
// scan history, detected changes, alerts, and health trend.
//
// Scope note:
//   executive.* fields (health_score, health_grade, priority_actions, ai_insight)
//   are NOT in this file. Those are provisional derived fields pending the Board's
//   Derived Intelligence policy ratification. See fields/derived.js.
//
// ─────────────────────────────────────────────────────────────────────────────

export const MONITORING_FIELDS = Object.freeze([
  {
    id:               'monitoring.last_scan',
    canonicalName:    'last_scan',
    displayName:      'Last Scan',
    parentObject:     'Scan',
    domain:           'Monitoring',
    description:      'ISO 8601 timestamp of the most recent completed scan for this artist.',
    dataType:         'date',
    required:         false,
    defaultValue:     null,
    validationRule:   'ISO 8601 datetime string',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl', 'Executive Brief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.scan_count',
    canonicalName:    'scan_count',
    displayName:      'Scan Count',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Total number of scans completed for this artist in the Royaltē system.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.change_count',
    canonicalName:    'change_count',
    displayName:      'Changes Detected',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Number of changes detected between the most recent scan and the previous scan.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'Health Intelligence', 'MissionControl', 'Executive Brief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.alert_count',
    canonicalName:    'alert_count',
    displayName:      'Active Alerts',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Number of unresolved alerts currently active for this artist.',
    dataType:         'number',
    required:         false,
    defaultValue:     0,
    validationRule:   'non-negative integer',
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl', 'Executive Brief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.health_trend',
    canonicalName:    'health_trend',
    displayName:      'Health Trend',
    parentObject:     'Artist',
    domain:           'Monitoring',
    description:      'Direction of health score movement across recent scans: IMPROVING | STABLE | DECLINING | UNKNOWN.',
    dataType:         'enum',
    required:         false,
    defaultValue:     'UNKNOWN',
    validationRule:   'IMPROVING|STABLE|DECLINING|UNKNOWN',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'Health Intelligence', 'MissionControl', 'Executive Brief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'monitoring.last_change_type',
    canonicalName:    'last_change_type',
    displayName:      'Last Change Type',
    parentObject:     'ChangeEvent',
    domain:           'Monitoring',
    description:      'Category of the most recently detected change (CATALOG_UPDATE, RIGHTS_CHANGE, DISTRIBUTION_CHANGE, etc.).',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'MOST_RECENT',
    confidencePolicy: 'STATIC',
    sourcePriority:   [],
    consumers:        ['MonitoringIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
