// ─────────────────────────────────────────────────────────────────────────────
// Canonical Intelligence Platform™ — Music Rights™ Domain Fields
// ─────────────────────────────────────────────────────────────────────────────
//
// Music Rights™ owns all fields describing the ownership and administration
// of an artist's compositions and recordings: PRO affiliation, publisher,
// record label, distributor, IPI, ISWC, and rights registration status.
//
// ─────────────────────────────────────────────────────────────────────────────

export const RIGHTS_FIELDS = Object.freeze([
  {
    id:               'rights.pro',
    canonicalName:    'pro',
    displayName:      'PRO Affiliation',
    parentObject:     'Artist',
    domain:           'Music Rights',
    description:      'Performing Rights Organization (ASCAP, BMI, SESAC, etc.) the artist is affiliated with.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc', 'musicbrainz', 'discogs'],
    consumers:        ['PublishingIntelligence', 'HealthEngine', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.publisher',
    canonicalName:    'publisher',
    displayName:      'Music Publisher',
    parentObject:     'Publisher',
    domain:           'Music Rights',
    description:      'Music publisher administering composition rights for the artist\'s catalog.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc', 'musicbrainz'],
    consumers:        ['PublishingIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.record_label',
    canonicalName:    'record_label',
    displayName:      'Record Label',
    parentObject:     'RecordLabel',
    domain:           'Music Rights',
    description:      'Record label holding the master recording rights for this artist.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz', 'discogs'],
    consumers:        ['PublishingIntelligence', 'IdentityIntelligence', 'MissionControl', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.distributor',
    canonicalName:    'distributor',
    displayName:      'Distributor',
    parentObject:     'Distributor',
    domain:           'Music Rights',
    description:      'Digital distributor responsible for delivering the artist\'s catalog to platforms.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc', 'musicbrainz'],
    consumers:        ['PublishingIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.publishing_administrator',
    canonicalName:    'publishing_administrator',
    displayName:      'Publishing Administrator',
    parentObject:     'PublishingAdministrator',
    domain:           'Music Rights',
    description:      'Entity administering publishing rights on behalf of a publisher or songwriter (e.g. Songtrust).',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc'],
    consumers:        ['PublishingIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.ipi_number',
    canonicalName:    'ipi_number',
    displayName:      'IPI Number',
    parentObject:     'Contributor',
    domain:           'Music Rights',
    description:      'Interested Parties Information number — global standard identifier for composers and publishers.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   '11-digit numeric string',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc', 'musicbrainz'],
    consumers:        ['PublishingIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.iswc',
    canonicalName:    'iswc',
    displayName:      'ISWC',
    parentObject:     'Work',
    domain:           'Music Rights',
    description:      'International Standard Musical Work Code — globally unique identifier for a musical composition.',
    dataType:         'string',
    required:         false,
    defaultValue:     null,
    validationRule:   'T-XXXXXXXXX-C format',
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc', 'musicbrainz'],
    consumers:        ['PublishingIntelligence', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.ownership_type',
    canonicalName:    'ownership_type',
    displayName:      'Ownership Type',
    parentObject:     'Artist',
    domain:           'Music Rights',
    description:      'Classification of the artist\'s rights structure: MAJOR | INDIE | SELF_RELEASED | UNKNOWN.',
    dataType:         'enum',
    required:         false,
    defaultValue:     'UNKNOWN',
    validationRule:   'MAJOR|INDIE|SELF_RELEASED|UNKNOWN',
    resolutionPolicy: 'DERIVED',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['apple', 'spotify', 'musicbrainz'],
    consumers:        ['PublishingIntelligence', 'HealthEngine', 'ExecutiveBrief'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
  {
    id:               'rights.mlc_registered',
    canonicalName:    'mlc_registered',
    displayName:      'MLC Registered',
    parentObject:     'Artist',
    domain:           'Music Rights',
    description:      'Whether the artist\'s compositions are registered with The MLC.',
    dataType:         'boolean',
    required:         false,
    defaultValue:     null,
    validationRule:   null,
    resolutionPolicy: 'CANONICAL_SOURCE',
    confidencePolicy: 'PROVIDER_TRUST',
    sourcePriority:   ['mlc'],
    consumers:        ['PublishingIntelligence', 'HealthEngine', 'MissionControl'],
    version:          '1.0.0',
    status:           'ACTIVE',
  },
]);
