-- ─────────────────────────────────────────────────────────────────────────────
-- Royaltē — Executive Brief Archive™ — ATHENA™ Phase 3A
--
-- DRAFT — NOT YET APPLIED. Per Executive Board directive (2026-07-24), this
-- migration must not be applied to any environment until the accompanying
-- architecture note (governance/ATHENA_PHASE3A_EXECUTIVE_BRIEF_ARCHIVE_ARCHITECTURE.md)
-- has been reviewed and explicitly approved. This file is a review artifact.
--
-- Permanent, immutable historical record of every archived Executive
-- Intelligence Object™. One row per successfully archived Executive Brief.
-- Rows are never updated after insert and never hard-deleted — see the
-- architecture note §"Immutability Rule" for the full reasoning.
--
-- Idempotent. Safe to re-run once applied.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

CREATE TABLE IF NOT EXISTS public.executive_brief_archive (
  id                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Business identity — see architecture note §Idempotency for why this is
  -- NOT the sole uniqueness anchor (the random 6-digit suffix is not
  -- database-guaranteed unique on its own).
  executive_brief_id              text NOT NULL,

  -- Ownership. NOT NULL by design — anonymous/unauthenticated scans are
  -- never archived (see architecture note §Data Ownership and Security).
  artist_profile_id               uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Provenance back to the originating scan. audit_scans.id IS the
  -- handler-generated scanId (api/audit.js) -- a real FK, not a loose text field.
  scan_id                         uuid REFERENCES public.audit_scans(id) ON DELETE SET NULL,

  generated_at                    timestamptz NOT NULL,

  -- Version metadata -- mirrors ExecutiveIntelligenceObject.metadata verbatim,
  -- duplicated into structured columns for efficient querying without
  -- unpacking the jsonb snapshot on every list/filter query.
  executive_version                text NOT NULL,
  schema_version                   text NOT NULL,
  pipeline_version                 text,
  athena_version                   text NOT NULL,
  runtime_context_version          text,

  -- Structured summary fields -- mirror EIO top-level fields, for
  -- list/filter/sort without touching the jsonb payload.
  confidence_level                 text NOT NULL, -- 'HIGH' | 'MEDIUM' | 'LOW' | 'INSUFFICIENT_DATA'
  critical_issue_count             integer NOT NULL DEFAULT 0,
  risk_count                       integer NOT NULL DEFAULT 0,
  opportunity_count                integer NOT NULL DEFAULT 0,
  recommendation_count             integer NOT NULL DEFAULT 0,

  -- Row lifecycle marker. 'archived' is the only value Phase 3A ever
  -- writes -- a failed archive attempt produces NO row at all (see
  -- architecture note §Archive Failure Behaviour: presence of a row IS the
  -- success signal). Reserved for future controlled values (Phase 3B+),
  -- never an overwrite of an existing row's snapshot.
  archive_status                   text NOT NULL DEFAULT 'archived',

  -- Full immutable snapshot -- the complete ExecutiveIntelligenceObject as
  -- returned to the client at generation time. Never partially updated.
  executive_intelligence_object    jsonb NOT NULL,

  -- Archive Integrity(tm) (Board amendment, 2026-07-24). SHA-256 hex digest
  -- of executive_intelligence_object, computed server-side immediately
  -- before this row is written. Lets a later export, comparison, or
  -- support/compliance investigation verify the archived record has not
  -- changed since the moment ATHENA generated it.
  archive_integrity_hash           text NOT NULL,

  -- Reserved for future extensibility (Board amendment, 2026-07-24) --
  -- Executive Brief comparison groupings, milestone grouping, release
  -- campaign snapshots, quarterly executive reporting. Always NULL in
  -- Phase 3A; adding the column now avoids a future migration.
  comparison_group_id              uuid,

  created_at                       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.executive_brief_archive IS
  'Executive Brief Archive(tm) -- permanent, immutable historical record of every
   archived Executive Intelligence Object(tm). Written exclusively server-side
   (service-role key) by the Executive Intelligence Pipeline(tm) write path. Rows are
   never updated after insert and never hard-deleted. Foundation for ATHENA(tm) Phase
   3B (Executive Timeline(tm), Executive Memory(tm), Cross-Scan Trend Intelligence(tm),
   Executive Comparison(tm)).';

COMMENT ON COLUMN public.executive_brief_archive.executive_brief_id IS
  'Business-facing immutable identifier (EB-YYYY-MM-DD-XXXXXX), generated by
   api/athena/executive-intelligence-object.js. NOT the sole uniqueness anchor --
   see the (artist_profile_id, scan_id) unique constraint below.';

COMMENT ON COLUMN public.executive_brief_archive.archive_status IS
  'Always "archived" as written by Phase 3A -- a failed write produces no row.
   Reserved for future controlled lifecycle values; never used to silently
   rewrite a prior assessment.';

COMMENT ON COLUMN public.executive_brief_archive.archive_integrity_hash IS
  'Archive Integrity(tm) -- SHA-256 hex digest of executive_intelligence_object,
   computed immediately before persistence. Verifies the archived record has not
   changed since generation.';

COMMENT ON COLUMN public.executive_brief_archive.comparison_group_id IS
  'Reserved for future use (Executive Brief comparison, milestone grouping,
   release campaign snapshots, quarterly reporting). Always NULL in Phase 3A.';

-- ── Idempotency / duplicate protection ──────────────────────────────────────
-- One archived Executive Brief per (artist, scan). A retried request, a
-- retried serverless invocation, or the same scan generating Executive
-- Intelligence more than once must all converge on the same row -- the write
-- path catches the unique-violation on this constraint and returns the
-- existing row's executive_brief_id instead of inserting a duplicate.
CREATE UNIQUE INDEX IF NOT EXISTS uq_executive_brief_archive_artist_scan
  ON public.executive_brief_archive(artist_profile_id, scan_id)
  WHERE scan_id IS NOT NULL;

-- Defense in depth against the (rare, per governance/ATHENA_EXECUTIVE_INTELLIGENCE_PHASE1_IMPLEMENTATION.md
-- §15's flagged limitation) random-suffix collision: two different scans
-- independently generating the identical executive_brief_id. The write path
-- catches this specific unique-violation and regenerates a new
-- executive_brief_id for the same EIO content, retrying a bounded number of
-- times -- see architecture note §Idempotency and Duplicate Protection.
CREATE UNIQUE INDEX IF NOT EXISTS uq_executive_brief_archive_brief_id
  ON public.executive_brief_archive(executive_brief_id);

CREATE INDEX IF NOT EXISTS idx_executive_brief_archive_artist_generated
  ON public.executive_brief_archive(artist_profile_id, generated_at DESC);

-- ── Row Level Security ──────────────────────────────────────────────────────
-- Mirrors the established royalty_statements convention: client-readable
-- (own rows only), never client-writable. All writes go through the
-- service-role key inside the Executive Intelligence Pipeline's server-side
-- write path -- RLS is defense-in-depth for reads, not the primary access
-- control (the read API in api/executive-brief-archive.js additionally
-- scopes every query to the Bearer-authenticated caller's own auth.uid()).

ALTER TABLE public.executive_brief_archive ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS executive_brief_archive_select_own ON public.executive_brief_archive;
CREATE POLICY executive_brief_archive_select_own
  ON public.executive_brief_archive
  FOR SELECT
  USING (auth.uid() = artist_profile_id);

-- No client INSERT/UPDATE/DELETE policies. The service role bypasses RLS
-- entirely for the write path; no policy would grant the browser write
-- access even if RLS were somehow disabled for authenticated users --
-- absence of a policy is a deny, not an implicit allow, per Postgres RLS
-- semantics with RLS enabled.

commit;
